version: '3'

services:
  react:
    build:
      context: ./react
    ports:
      - "3000:80"
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi/.env
