version: '3'

services:
  react:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend

  fastapi:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
